### ISSUE TITLE
Fail to read T1 from brainweb_dl when running example in MRI-NUFFT

### ISSUE THREAD

**Issue by wenshangwang** [paquiteau/brainweb-dl#4]
Dear Pierre-Antoine

I am trying to use your MRI-NUFFT package from my MRI research project. More specifically its ability to generate NUFFT operator considering the effect of a known off-resonance field. 

After installing everything needed for MRI-NUFFT and brainweb-dl, I was running the "Off-resonance corrected NUFFT operator" example. I would like your help for the error that I am encountering now. 

I downloaded your example code and run everything. This following error happened: 
![image](https://github.com/user-attachments/assets/906e0443-7376-4848-958b-7a15b8ab5c48)
![image](https://github.com/user-attachments/assets/b0040bfe-c27a-4082-8c1b-0f212cbbe457)
My guess is that get_mri did not successfully read the T1. 

What do you think might happened and what could be the way to debug?

Btw, I am really enjoying your NUFFT package and would love to keep in touch for future discussion. 

Best
Wenshang

**Comment by paquiteau** [comment]
Hi wenshang,
Which version of MRI-Nufft and brainweb-dl are you using ? (Be sure they are the latest, I had fix a similar bug a few weeks ago)

Also, have you try rerun the example ? Looking at the error it could be a download issue.

Thanks for your interest in MRI-NUFFT, feel free to let us know what you are using it for :)

**Comment by wenshangwang** [comment]
Thanks for you reply!

the brainweb-dl version is 0.3.0 and the mri-nufft is 0.11.0. I rerun the example a few time but the error did not go away.

The main purpose for me to run the example is to figure out what kind of array should the k-space trajectory be such that it would work for get_operator() function. I was able to find out that by running the initialize_2D_radial by itself and read the source code. The reason is my kspace data is sampled in EPI fashion (Cartesian grid, single shot) and Cartesian is not included in the package. 

I think I should generate a [1, NxN, 2] array for my trajectory representing the actual sampled locations [kx, ky] for all of the points I sampled. I guess density will not matter as this is uniformed cartesian. In your initialize trajectory code you make the kmax as a constant at 0.5. Is this just for the purpose of the example and I should properly scale my own k trajectory array by my actual acquisition kmax correct? I am wondering this because I don't see an input argument for value of kmax in get_operator. Please correct me if I am wrong. 

I am developing methods to do effective and novel offline reconstruction of our in-house developed EPI sequence so accounting all the artifacts such as off-resonance field is an important part of the job. I like the method of nufft because of its ability to incorporate non-uniform sampling effect into the signal equation. 

Best
Wenshang

**Comment by paquiteau** [comment]
Hi Wenshang, 

Unfortunately, I am not able to reproduce your bug. But I am not giving up. 

- Are you using Linux ?
- Let's see if you can download the data. Can you run the following in a terminal: 
```
curl -L 'http://brainweb.bic.mni.mcgill.ca/cgi/brainweb1/?do_download_alias=T1+ICBM+normal+1mm+pn0+rf0&format_value=raw_short&zip_value=gnuzip&download_for_real=%5BStart+download%21%5D' --compressed --output  rawT1.bin
```
This raw file should be ~8MB and have the following md5sum (get it using `md5sum rawT1.bin`) `0fc6186758dc2e17357e569dde29e41e`

If you are able to get the data like this, brainweb-dl should work.

**Comment by wenshangwang** [comment]
Pierre

Thank you very much for your effort! Yesterday I was able to find out why. It was because some package from my jupyter was missing and I need to update my own jupyter notebook in order to successfully execute the get_mri function. 

I do also have some question regarding using the MRI-NUFFT when we are creating our own trajectory and readout time matrix. Do you want to rather discuss those in a issue in the MRI-NUFFT repository? You can close this thread if you would like to do that. 

Again thank you very much for your timely reply and help. 

Wenshang

**Comment by paquiteau** [comment]
Let's discuss MRI-NUFFT in MRI-NUFFT repo, more people would be able to participate
